/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lyraTdd;

public class App {

    public static void main(String[] args) {
    }

    public String fizzBuzz(int n) {
        if (n % 3 == 0 && n % 5 == 0) {
            return "FizzBuzz";
        } else if (n % 3 == 0) {
            return "Fizz";
        } else if (n % 5 == 0) {
            return "Buzz";
        } else {
            return String.valueOf(n);
        }
    }
}
